def province():
    provinces = [
        ('Province 1','Province 1'), ('Province 2','Province 2'), ('Bagmati Pradesh','Bagmati Pradesh'), ('Gandaki Pradesh','Gandaki Pradesh'), ('Province 5','Province 5'),('Karnali Pradesh','Karnali Pradesh'),('Sudurpashchim Pradesh','Sudurpashchim Pradesh')
    ]
    return provinces

def skillslist():
    skills = [
        ('Farmer','Farmer'),
        ('Labourer','Labourer'),
        ('Factory Worker','Factory Worker'),
        ('Carpenter - Kathmistri','Carpenter - Kathmistri'),
        ('Mason - Rajmistri','Mason - Rajmistri'),
        ('Contractor - Thekedar','Contractor - Thekedar'),
        ('Delivery Rider/Driver','Delivery Rider/Driver'),
        ('Bus Driver','Bus Driver'),
        ('Bus Rental Services','Bus Rental Services'),
        ('Van Driver','Van Driver'),
        ('Van Rental Services','Van Rental Services'),
        ('Truck Driver','Truck Driver'),
        ('Truck Rental Services','Truck Rental Services'),
        ('Tractor Driver','Tractor Driver'),
        ('Tractor Rental Services','Tractor Rental Services'),
        ('Dozer/JCB Driver','Dozer/JCB Driver'),
        ('Dozer/JCB Rental Services','Dozer/JCB Rental Services'),
        ('Ambulance Driver','Ambulance Driver'),
        ('Ambulance Rental Services','Ambulance Rental Services'),
        ('Vehicle Repairing Center', 'Vehicle Repairing Center'),
        ('Mill Services', 'Mill Services'),
        ('Security Guard', 'Security Guard'),
        ('Housemaid', 'Housemaid'),
        ('Cleaner','Cleaner'),
        ('Septic Cleaner','Septic Cleaner'),
        ('Tailor','Tailor'),
        ('Painter', 'Painter'),
        ('Mechanic','Mechanic'),
        ('Mobile Repairer','Mobile Repairer'),
        ('Bus Mechanic','Bus Mechanic'),
        ('Electrician','Electrician'),
        ('Plumber','Plumber'),
        ('Butcher - Kasai','Butcher - Kasai'),
        ('Computer Mechanic','Computer Mechanic'),
        ('Sound DJ','Sound DJ'),
        ('Tent Decorator','Tent Decorator'),
        ('Chef', 'Chef'),
        ('Hotel', 'Hotel'),
        ('Restaurant', 'Restaurant'),
        ('Catering Server','Catering Server'),
        ('Food/Groceries Supplier','Food/Groceries Supplier'),
        ('Fruits Supplier', 'Fruits Supplier'),
        ('Stationery Supplier','Stationery Supplier'),
        ('Clothing Items Supplier','Clothing Items Supplier'),
        ('Hardware Supplier','Hardware Supplier'),
        ('Harvester','Harvester'),
        ('Photographer','Photographer'),
        ('House Decorator','House Decorator'),
        ('Agricultural Products Supplier', 'Agricultural Products Supplier'),
        ('Petrol Pump','Petrol Pump'),
        ('House Material Supplier','House Material Supplier'),
        ('Poultry/Chicken Supplier','Poultry/Chicken Supplier'),
        ('Fish Supplier','Fish Supplier'),
        ('Shopkeeper', 'Shopkeeper'),
        ('Dairy Products Supplier', 'Dairy Products Supplier'),
        ('Restaurant Waiter','Restaurant Waiter'),
        ('Restaurant Waitress','Restaurant Waitress'),
        ('Beautician - Parlour','Beautician - Parlour'),
        ('Barber - Hajam','Barber - Hajam'),
        ('Cobbler - Mochi', 'Cobbler - Mochi'),
        ('Teacher','Teacher'),
        ('School','School'),
        ('Tutor','Tutor'),
        ('Doctor','Doctor'),
        ('Nurse','Nurse'),
        ('Health Worker','Health Worker'),
        ('Web Developer/Designer','Web Developer/Designer'),
        ('Software Developer','Software Developer'),
        ('Programmer','Programmer'),
        ('Engineer','Engineer'),
        ('Architect','Architect'),
        ('Travel Agency','Travel Agency'),
        ('Tour Guide','Tour Guide'),
        ('Porter','Porter'),
        ('Sales Officer','Sales Officer'),
        ('Data Entry Officer','Data Entry Officer'),
        ('Receptionist','Receptionist'),
        ('Accountant','Accountant'),
        ('Bank Cashier','Bank Cashier'),
        ('Bank Staff','Bank Staff'),
        ('Lawyer - Wakil','Lawyer - Wakil'),
        ('News Reporter','News Reporter'),
        ('Journalist','Journalist'),
        ('Student Consultant Services', 'Student Consultant Services'),
        ('Marketer','Marketer'),
        ('Social Worker','Social Worker'),
        ('Volunteer','Volunteer'),
        ('Jyotish','Jyotish')
    ]
    return skills